"""fcm_tokens: add indexes, timestamps, platform default, upsert shape

Revision ID: 99e8318d07bb
Revises: e77f07e46f12
Create Date: 2025-08-18 08:20:58.610223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99e8318d07bb'
down_revision = 'e77f07e46f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcm_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('platform',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.drop_index(batch_op.f('token'))
        batch_op.create_index(batch_op.f('ix_fcm_tokens_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_fcm_tokens_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_fcm_tokens_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fcm_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcm_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fcm_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_fcm_tokens_session_id'))
        batch_op.drop_index(batch_op.f('ix_fcm_tokens_platform'))
        batch_op.drop_index(batch_op.f('ix_fcm_tokens_active'))
        batch_op.create_index(batch_op.f('token'), ['token'], unique=True)
        batch_op.alter_column('active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
